# -*- coding: utf-8 -*-
"""A Game of Chance.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1800a0dQx2WLIy7-ZulMHAblsvy5xsHrf
"""

import random

def roll_dice():
    """Roll two six-sided dice and return their values."""
    die1 = random.randint(1, 6)
    die2 = random.randint(1, 6)
    return die1, die2

def main():
    print("Selamat datang di permainan Craps!")

    while True:
        input("Tekan Enter untuk melempar dadu...")
        die1, die2 = roll_dice()
        sum_dice = die1 + die2
        print(f"Anda melempar {die1} + {die2} = {sum_dice}")

        # Determine the outcome based on the first roll
        if sum_dice in (7, 11):
            print("Anda menang!")
            break
        elif sum_dice in (2, 3, 12):
            print("Craps! Anda kalah!")
            break
        else:
            # Establish the point
            point = sum_dice
            print(f"Point Anda adalah {point}. Terus melempar untuk mencapai point Anda.")

            while True:
                input("Tekan Enter untuk melempar dadu lagi...")
                die1, die2 = roll_dice()
                sum_dice = die1 + die2
                print(f"Anda melempar {die1} + {die2} = {sum_dice}")

                if sum_dice == point:
                    print("Anda mencapai point Anda! Anda menang!")
                    break
                elif sum_dice == 7:
                    print("Anda melempar angka 7. Anda kalah!")
                    break
            break

if __name__ == "__main__":
    main()